version: '2'

services:
  wordpress:
    restart: always
    container_name: wordpress
    build: images/wordpress
    working_dir: /var/www/html/wordpress
    volumes:
      - ./wordpress:/var/www/html/wordpress
    environment:
      - "ENV=development"
      - "WORDPRESS_DB_NAME=wordpress"
      - "WORDPRESS_DB_USER=wordpress"
      - "WORDPRESS_DB_HOST=wordpress_db:3306"
      - "WORDPRESS_DB_PASSWORD=password"

  wordpress_nginx:
    restart: always
    container_name: wordpress_nginx
    build: images/nginx
    volumes_from:
      - wordpress
    volumes:
      - ./logs:/var/www/logs
    ports:
      - 80:80

  wordpress_db:
    restart: always
    container_name: wordpress_db
    image: mariadb:latest
    environment:
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
